export enum UI {
    Main = 'UIMain',
    Level = 'UILevel',
    Game = 'UIGame',
    Pause = 'UIPause',
    Win = 'UIWin',
    SuperWin = 'UISuperWin',
    Fail = 'UIFail',
    Confirm = 'UIConfirm',
    Setting = 'UISetting',
    Top = 'UITop',
    Toast = 'UIToast',
    SideBar = 'UISideBar',
    Rank = 'UIRank',
    Replay = 'UIReplay',
    Revive = 'UIRevive',
    Skill = 'UISkill',
    Transition = 'UITransition',
    Collect = 'UICollect',
    CollectInfo = 'UICollectInfo',
    Gashapon = 'UIGashapon',
    GetReward = 'UIGetReward',
    Decoration = 'UIDecoration',
    StageTip = 'UIStageTip',
    Home = 'UIHome',
    PassReward = 'UIPassReward',
    ShareVideo = 'UIShareVideo'
}

